set number
set nowrap
set incsearch
set ignorecase
set smartcase
set backup
set writebackup
set swapfile

set tabstop=4
set shiftwidth=4
set expandtab
set noic

call pathogen#infect() 

nnoremap <C-t> :<C-u>FufFile **/<CR>

filetype plugin on
let g:pymode_folding = 0
