#!/usr/bin/python
import dbus
import sys

def __triggerAction(action):
    try:
         bus = dbus.SessionBus()
         player = bus.get_object('com.spotify.qt', '/')
         iface = dbus.Interface(player, 'org.freedesktop.MediaPlayer2')
         if action: return getattr(iface, action)()
         print 'GetMetadata Next Pause Play PlayPause Previous Quit Stop'
        
    except Exception, e: print e

if __name__ == "__main__":
    __triggerAction(sys.argv[1] if len(sys.argv) > 1 else None)
